import type { Metadata } from 'next'
import { Nanum_Gothic } from 'next/font/google'
import './globals.css'

const nanumGothic = Nanum_Gothic({ subsets: ["latin"], weight: ["400", "700", "800"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="kr">
      <body className={nanumGothic.className}>{children}</body>
    </html>
  )
}
